### ISSUE TITLE
any way to close pool?

### ISSUE THREAD

**Issue by andriybohdan** [shorrockin/cascal#1]
Hello

I'm using the following code:

```
val hosts  = Host("127.0.0.1", 9160, 250) :: Nil  
val params = new PoolParams(10, ExhaustionPolicy.Fail, 500L, 6, 2)
var pool   = new SessionPool(hosts, params, Consistency.One)

pool.borrow { session => 
  println("Count Value: " + session.count("KS" \ "CF" \ "K"))
}
```

Output:

```
Apr 6, 2010 6:43:53 PM com.shorrockin.cascal.session.SessionPool$SessionFactory$ makeSession
FINE: attempting to create connection to: Host(127.0.0.1,9160,250)
Count Value: 308
Apr 6, 2010 6:43:56 PM com.shorrockin.cascal.session.SessionPool$SessionFactory$ makeSession
FINE: attempting to create connection to: Host(127.0.0.1,9160,250)
Apr 6, 2010 6:43:56 PM com.shorrockin.cascal.session.SessionPool$SessionFactory$ makeSession
FINE: attempting to create connection to: Host(127.0.0.1,9160,250)
Apr 6, 2010 6:43:59 PM com.shorrockin.cascal.session.SessionPool$SessionFactory$ makeSession
FINE: attempting to create connection to: Host(127.0.0.1,9160,250)
Apr 6, 2010 6:44:02 PM com.shorrockin.cascal.session.SessionPool$SessionFactory$ makeSession
FINE: attempting to create connection to: Host(127.0.0.1,9160,250)
```

Stack:

CassandraTestSuite [Scala Application]  
    org.scalatest.tools.Runner at localhost:46530  
        Thread [main](Running) 
        Thread [AWT-Shutdown](Running) 
        Daemon Thread [AWT-XAWT](Running)  
        Thread [AWT-EventQueue-0](Running) 
        Daemon Thread [Timer-0](Running)  
        Daemon Thread [Timer-1](Running)  
    /usr/lib/jvm/java-6-sun-1.6.0.15/bin/java (Apr 6, 2010 6:45:16 PM)  

The program never ends. Is there any way to shutdown pool threads and stop the process?

This library looks the most promising at least by documentation :)

Thanks!

**Comment by shorrockin** [comment]
That is a shocking oversight, that, funny enough I ran into myself today during some integration tests. I'll have a fix within the next few hours.

**Comment by andriybohdan** [comment]
Please disregard this issue. My problem is related to testing framework.

**Comment by andriybohdan** [comment]
Okay :) I suspect the 2 additional threads in the stack trace were created by scalatest objects. 
I've tried to run the same code without testing wrapper and it ends immediately.

**Comment by shorrockin** [comment]
Oh - Great! While your testing framework may be keeping the JVM alive - The connection pool is missing the methods to close all resources associated with it. So I'll still add the methods that should be there.

**Comment by shorrockin** [comment]
fixed in master (http://bit.ly/9aKwJM) - will deploy to the maven repository as part of the 1.1-SNAPSHOT version later tonight.

**Comment by andriybohdan** [comment]
Looks nice! It must help to save memory and other resources when it's important.
