### ISSUE TITLE
Untitled

### ISSUE THREAD

**Issue by boegemann** [shorrockin/cascal#18]

**Comment by shorrockin** [comment]
was this an accidental post? or?

**Comment by boegemann** [comment]
This was accidental - I couldn't find a way to delete it again ....

However whilst I have your attention:
Is there an elegant way to return values from a 'borrow' block?
Currently I assign it to a pre-defined var which I then return outside of the borrow block.
Thanks
Ingo

**Comment by shorrockin** [comment]
If you the master branch (or 1.2-SNAPSHOT in maven) in maven then borrow should return the value of the function passed in. That is:

val value = pool.borrow { _.get("KS" \ "CF" \ "Col") }

Which should do what you need. Let me know if you're thinking of something else.

**Comment by boegemann** [comment]
Thanks - That's exactly it! 
So much neater!
Thanks for a fab library
