### ISSUE TITLE
is there a way to create a KeyRange using non-string keys?

### ISSUE THREAD

**Issue by jstrachan** [shorrockin/cascal#19]
I was wondering how to do a slice of keys which are not strings? KeyRange seems to only use Strings. What if I wanted to do Session.list for a range of byte keys?

Is this a time you've gotta just use the Cassandra client directly?

**Comment by shorrockin** [comment]
keys in Cassandra are always strings, while you may use some other values within Cassandra they are always represented as UTF-8 string values (however - I believe I read something about this changing in 0.7). 

The KeyRange case class in Cascal is a fairly simplistic wrapper on org.apache.cassandra.thrift.KeyRange which also deals with String values so unfortunately even if you were to use the Cassandra client directly you would still have this limitation of key ranges. 

Let me know if this is unclear.

**Comment by scalate** [comment]
Doh :) spot the cassandra newbie :)

I thought keys were bytes as you can sort them in time order and all that - never mind, sorry for the noise. I'm really liking cascal BTW!

**Comment by jstrachan** [comment]
feel free to close this issue now! thanks for your prompt response

**Comment by jstrachan** [comment]
closing...
