### ISSUE TITLE
extract a trait for the public Session API so its easier to tweak pooling and compose Cascal code

### ISSUE THREAD

**Issue by jstrachan** [shorrockin/cascal#21]
it would be great if we could separate out the Session API to a trait so that it can be implemented in various ways. e.g. here's a few possible implementations...
- use a direct session implementation (like the current Session class)
- each operation would use SessionPool.borrow to grab a session from the pool, do the work then return the session to the pool
- lazily associate the calling thread a session from the pool using a ThreadLocal (which maybe after an inactive time is then returned to the pool when its not being used). Kinda like the above but basically let methods in the same thread use the same session 
- share a single session implementation across a number of threads (kinda like option 2)

In some Cascal code I've found the number of sessions used can greatly affect performance (seems lots of sessions seem to slow cassandra down) so it might be nice to make it easy to tinker with how physical sessions are pooled/shared across threads.

Another issue this helps solve is it soon gets tricky to compose lots of code passing around the pool and/or the current session we've grabbed from the pool (in case another thread accidentally reuses a session from another thread). So hiding the pooling bit really helps keep code clean and correct.

e.g. in the Spring Framework there are lots of 'pool' type objects; JmsTemplate, JdbcTemplate, HibernateTemplate, JpaTemplate and many others. All of them hide how the pool works (usually grabbing one from the pool, associating it with a thread until the operation/transaction completes etc).

For example if we had a trait called SessionTemplate which mirrored the public API of Session right now - then different implementations which either used a pool, or used a single session under the covers with locking or whatever - then user Cascal code could just pass the SessionTemplate around everywhere across threads - then the implementation could be chosen to best suit the applications threading model (after performance tuning and experimentation).

It would also let folks implement their own pools if they want.

**Comment by shorrockin** [comment]
Great suggestion - I'll look into making the changes to address this. Thanks for the feedback.

**Comment by shorrockin** [comment]
Based on this suggestion I've made the change in http://github.com/shorrockin/cascal/commit/00c218e3a66c0f03249b75e67703c8edc82c6e41.
- trait added SessionTemplate
- Session now extends SessionTemplate (use case #1 above)
- SessionPool now extends SessionTemplate (use case #2 above)

The thread local based one is pretty specific to the application for which it's being used under so I'm not sure a default implementation of those use-cases belong here.

changes in maven as 1.2-SNAPSHOT. Let me know if anything seems off.

**Comment by jstrachan** [comment]
Awesome stuff - that looks perfect! Will give it a try...

**Comment by shorrockin** [comment]
Cleaning up old closed items.
