### ISSUE TITLE
Timestamps should be microseconds rather than milliseconds

### ISSUE THREAD

**Issue by takezoux2** [shorrockin/cascal#22]
Now timestamps are set milliseconds if I use overloaded com.shorrockin.cascal.model.Column constructors.(In code , they are generated by System.currentTimeMillis or new Date.getTime.)

Buy in Cassandra wiki,it is recommended to use microseconds.
I think they should be microseconds.

http://wiki.apache.org/cassandra/DataModel#Columns
written:
Timestamps can be anything you like, but microseconds since 1970 is a convention. 

Attached client "cassandra-cli" sets microseconds timestamp.So if I set or delete column value with cassandra-cli, I can't update that column with cascal!

**Comment by shorrockin** [comment]
Fair point - currently on vacation but i'll look into it when I get back

**Comment by chirino** [comment]
takezoux2, should be fixed in branch http://github.com/chirino/cascal

Lets us know if it works for you.

**Comment by shorrockin** [comment]
Thanks a ton chirino for all your work on this one. I tried to pull in the changes this morning but my connection on my laptop is real poor. I'll be sure to pull and deploy this changes first thing Saturday when I get back. Thanks again!

**Comment by shorrockin** [comment]
Fixed in branch. As soon as 2.8 finalizes branch will be merged into main.
