### ISSUE TITLE
Maven Repo

### ISSUE THREAD

**Issue by cemmersb** [shorrockin/cascal#30]
Dear all,

seems like the maven repo is offline.

Can somebody double check on that topic?

Many greets and kind regards,

Christoph

**Comment by dosht** [comment]
+1

**Comment by shorrockin** [comment]
Howdy - Unfortunately this project is no longer being maintained, including the maven repository that I used to host off my own private server. 

That said, it should be easy enough to build and host things yourself. Apologies, and cheers.
